import type { KpiDefinition } from '../types.js';

/** Complete registry of all known KPIs */
export const KPI_REGISTRY: KpiDefinition[] = [
  // ── Flow ──────────────────────────────────────────────────────
  {
    id: 'pickup_latency',
    name: 'Pickup Latency',
    category: 'flow',
    unit: 'hours',
    description: 'Time from task creation to first assignment (p50/p90)',
    data_source: 'productivity_events',
  },
  {
    id: 'first_progress',
    name: 'First Progress',
    category: 'flow',
    unit: 'hours',
    description: 'Time from assignment to first status change (p50/p90)',
    data_source: 'productivity_events',
  },
  {
    id: 'review_wait',
    name: 'Review Wait',
    category: 'flow',
    unit: 'hours',
    description: 'Time a task waits in review before approval (p50/p90)',
    data_source: 'github',
  },
  {
    id: 'cycle_time',
    name: 'Cycle Time',
    category: 'flow',
    unit: 'hours',
    description: 'End-to-end time from task start to completion (p50/p90)',
    data_source: 'productivity_events',
  },
  {
    id: 'blocked_age',
    name: 'Blocked Age',
    category: 'flow',
    unit: 'hours',
    description: 'How long currently-blocked tasks have been blocked (p50/max)',
    data_source: 'queue',
  },
  {
    id: 'throughput',
    name: 'Throughput',
    category: 'flow',
    unit: 'count',
    description: 'Tasks completed in the last 24h and 7d windows',
    data_source: 'productivity_events',
  },
  {
    id: 'completion_throughput',
    name: 'Completion Throughput',
    category: 'flow',
    unit: 'count',
    description: 'Tasks reaching verified-done with tool-backed evidence per window',
    data_source: 'execution',
  },
  {
    id: 'reopen_rate',
    name: 'Reopen Rate',
    category: 'flow',
    unit: 'percent',
    description: 'Fraction of completed tasks reopened within the sample window',
    data_source: 'productivity_events',
  },

  // ── Capacity ──────────────────────────────────────────────────
  {
    id: 'wip_by_owner',
    name: 'WIP by Owner',
    category: 'capacity',
    unit: 'count',
    description: 'Work-in-progress distribution across individual owners',
    data_source: 'queue',
  },
  {
    id: 'wip_by_pod',
    name: 'WIP by Pod',
    category: 'capacity',
    unit: 'count',
    description: 'Work-in-progress distribution across pods/teams',
    data_source: 'queue',
  },
  {
    id: 'idle_with_work',
    name: 'Idle with Work',
    category: 'capacity',
    unit: 'count',
    description: 'Number of agents that are idle despite available work in the queue',
    data_source: 'queue',
  },
  {
    id: 'owner_concentration',
    name: 'Owner Concentration',
    category: 'capacity',
    unit: 'percent',
    description: 'Herfindahl index of task ownership concentration',
    data_source: 'queue',
  },
  {
    id: 'unassigned_backlog_age',
    name: 'Unassigned Backlog Age',
    category: 'capacity',
    unit: 'hours',
    description: 'Age of oldest unassigned items in the backlog (p50/max)',
    data_source: 'queue',
  },

  // ── Runtime ───────────────────────────────────────────────────
  {
    id: 'intervention_effectiveness',
    name: 'Intervention Effectiveness',
    category: 'runtime',
    unit: 'percent',
    description: 'Fraction of operator interventions that resolved the issue',
    data_source: 'productivity_events',
  },
  {
    id: 'no_signal_rate',
    name: 'No-Signal Rate',
    category: 'runtime',
    unit: 'percent',
    description: 'Fraction of telemetry packets arriving with no meaningful signal',
    data_source: 'execution',
  },
  {
    id: 'stale_lanes',
    name: 'Stale Lanes',
    category: 'runtime',
    unit: 'count',
    description: 'Number of workflow lanes with no activity beyond threshold',
    data_source: 'queue',
  },
  {
    id: 'deadlock_escalations',
    name: 'Deadlock Escalations',
    category: 'runtime',
    unit: 'count',
    description: 'Number of deadlock situations escalated to operator',
    data_source: 'productivity_events',
  },
  {
    id: 'retarget_breaches',
    name: 'Retarget Breaches',
    category: 'runtime',
    unit: 'count',
    description: 'Number of interventions that breached retarget cap',
    data_source: 'productivity_events',
  },

  // ── Execution ─────────────────────────────────────────────────
  {
    id: 'tool_backed_runs',
    name: 'Tool-Backed Runs',
    category: 'execution',
    unit: 'count',
    description: 'Execution runs backed by at least one tool invocation',
    data_source: 'execution',
  },
  {
    id: 'verified_completions',
    name: 'Verified Completions',
    category: 'execution',
    unit: 'count',
    description: 'Runs completed with tool-backed evidence of success',
    data_source: 'execution',
  },
  {
    id: 'intent_only_runs',
    name: 'Intent-Only Runs',
    category: 'execution',
    unit: 'count',
    description: 'Runs with intent claim but no lifecycle evidence',
    data_source: 'execution',
  },
  {
    id: 'silent_accepted_runs',
    name: 'Silent Accepted Runs',
    category: 'execution',
    unit: 'count',
    description: 'Runs accepted without evidence of meaningful work',
    data_source: 'execution',
  },
];
